print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/timseifert/Week-4-Game-Design/Assets/Art/Character/Paparazzi/pap_a_0.ma"`)
{		
	file -o "/Users/timseifert/Week-4-Game-Design/Assets/Art/Character/Paparazzi/pap_a_0.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/timseifert/Week-4-Game-Design/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/timseifert/Week-4-Game-Design/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/timseifert/Week-4-Game-Design/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
