print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/Documents/GitHub/GameDesignWkFour/Assets/Art/Character/Paparazzi/pap_a_0.ma"`)
{		
	file -o "D:/Documents/GitHub/GameDesignWkFour/Assets/Art/Character/Paparazzi/pap_a_0.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/Documents/GitHub/GameDesignWkFour/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/Documents/GitHub/GameDesignWkFour/Temp/CommandPipe";

$donepipeKill = `fopen "D:/Documents/GitHub/GameDesignWkFour/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
